Add Synapse connected buckets for data proc jobs
Sage-Bionetworks/scicomp-provisioner pull request #460
Opened 2021-04-29 19:01 UTC by ahayden

- [x] This change makes uat/prod buckets connected to synapse and owned by Synapse service accounts. These are the for the output of data processing jobs that will run in scicomp, including for app migration and for R proc
- [x] Passes pre-commit

2021-05-03 17:51 UTC, zaro0508 requested changes

2021-05-03 17:51 UTC, zaro0508 commented on config/prod/dian-prod-synapse-import-s3.yaml
> +  SameRegionResourceAccessToBucket: "true"
Enabling this only make sense if you `GrantAccess` to users that might download files from regions outside of us-east-1.  Wondering why you are enabling this when the only thing that has access is synapse?

2021-05-03 17:53 UTC, zaro0508 requested changes

2021-05-03 17:53 UTC, zaro0508 commented on config/prod/dian-prod-synapse-import-s3.yaml
> +  Project: "DIAN"
hmm, the Platform dept has a DIAN project?

2021-05-03 17:53 UTC, zaro0508 commented on config/prod/dian-prod-synapse-import-s3.yaml
> +    - !cmd "wget https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/s3-bucket-v2.j2 -N -P templates/remote"
i would recommend pinning to the latest tag.

2021-06-28 17:19 UTC, ahayden commented
Closing as will be superseded by PR based on new templates

2021-06-28 17:19 UTC, closed without merging