create mini dream 2022 ec2 and alb
Sage-Bionetworks/scicomp-provisioner pull request #522
Opened 2022-05-12 17:22 UTC by linglp

This PR is related to the issue here [#issue](https://github.com/Sage-Bionetworks/minidream-r-env/issues/22). We need to provision an EC2 instance for Mini dream 2022.  This PR is based on the PR in previous year [here](https://github.com/Sage-Bionetworks/scicomp-provisioner/pull/504/files)

We have run `pre-commit` for our files: 
```
(venv) lpeng@w153 scicomp-provisioner % pre-commit run --files config/prod/minidream*
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
yamllint.................................................................Passed
AWS CloudFormation Linter............................(no files to check)Skipped
Tabs remover.............................................................Passed
check file names.........................................................Passed
check stack names........................................................Passed
check stack tags.........................................................Passed

```

2022-05-12 17:23 UTC, BrunoGrandePhD commented on config/prod/minidream-rstudio-2022-ec2.yaml
> +    - !ec2_notify "{{stack_group_config.aws_account_name}} {{stack_group_config.aws_account_email}}"
@zaro0508: Is this still needed?

2022-05-12 19:36 UTC, BrunoGrandePhD commented on config/prod/minidream-rstudio-2022-ec2.yaml
> +  InstanceType: "x1.16xlarge"     # 64 vCPUs / 976 GiB / 1920 GiB SSD
We need to switch to `x2gd.8xlarge`.

2022-05-12 21:39 UTC, linglp commented on config/prod/minidream-rstudio-2022-ec2.yaml
> +  InstanceType: "x1.16xlarge"     # 64 vCPUs / 976 GiB / 1920 GiB SSD
Okay! I just updated it. Thanks Bruno!

2022-05-13 19:01 UTC, zaro0508 requested changes
The pre-commit validation is failing on the CI system because your not validating all files.  Please run `pre-commit run --all-files` on your local machine to validate all files.

2022-05-13 19:53 UTC, zaro0508 commented on config/prod/minidream-rstudio-2022-ec2.yaml
> +  AMIId: "ami-0b7906ab614596e7e"  # packer-base-ubuntu-bionic-v1.0.9
PR to update this AMI is here https://github.com/Sage-Bionetworks-IT/packer-base-ubuntu-bionic/pull/30

2022-05-13 20:39 UTC, BrunoGrandePhD commented on config/prod/minidream-rstudio-2022-ec2.yaml
> +  AMIId: "ami-0b7906ab614596e7e"  # packer-base-ubuntu-bionic-v1.0.9
I see that the new image just finished [building now](https://github.com/Sage-Bionetworks-IT/packer-base-ubuntu-bionic/runs/6429224934). According to [this line](https://app.travis-ci.com/github/Sage-Bionetworks-IT/packer-base-ubuntu-bionic/jobs/570192494#L7620), the new image ID is `ami-0a3c3e0cb6ae0cc6c`. 

I'm not sure if the [AMI Dashboard](https://ami.sageit.org/) is updated automatically or not.

2022-05-13 20:39 UTC, zaro0508 commented on config/prod/minidream-rstudio-2022-ec2.yaml
> +  AMIId: "ami-0b7906ab614596e7e"  # packer-base-ubuntu-bionic-v1.0.9
a new [packer-base-ubuntu-bionic-v1.0.10](https://github.com/Sage-Bionetworks-IT/packer-base-ubuntu-bionic/tags) has been [created and deployed](https://app.travis-ci.com/github/Sage-Bionetworks-IT/packer-base-ubuntu-bionic/jobs/570192494).  Please update with new AMI id `ami-0a3c3e0cb6ae0cc6c`

2022-05-13 21:17 UTC, linglp commented on config/prod/minidream-rstudio-2022-ec2-alb.yaml
> +# Also, update DNS for minidream.synapse.org to point to this ALB once deployed.
> 

@zaro0508 I have run `pre-commit run --all-files` locally and made sure that all files passed the check. My new commits should have the styling errors fixed. Thanks!

2022-05-13 21:20 UTC, linglp commented
@zaro0508 could you review again? I have updated my PR based on your comment. Thanks!

2022-05-16 15:51 UTC, zaro0508 approved these changes

2022-05-16 18:33 UTC, merged