Pec globus
Sage-Bionetworks/scicomp-provisioner pull request #533
Opened 2022-07-27 15:22 UTC by danlu1

This PR includes:
1. A template that supports both Synapse and Globus. This template is derived from [synapse-external-bucket.j2](https://github.com/Sage-Bionetworks/aws-infra/blob/master/templates/S3/synapse-external-bucket.j2) and I added actions based on this [instruction](https://globus.stanford.edu/cloud/s3.html#:~:text=Replace%20that%20null%20policy%20with%20the%20following%20JSON%3A).

2. A config yaml to provision the S3 and grant synapse and Dan's sandbox account access for now. 

depends on https://github.com/Sage-Bionetworks/aws-infra/pull/349

2022-07-27 16:01 UTC, zaro0508 commented on config/prod/PsychENCODE-Globus-S3.yaml
> +  url: ""
you don't need `templates/PEC-Globus-S3.j2`.  You just need to reference the [synapse-external-bucket.j2 file](https://github.com/Sage-Bionetworks/aws-infra/blob/master/templates/S3/synapse-external-bucket.j2)

2022-07-27 16:06 UTC, zaro0508 commented on config/prod/PsychENCODE-Globus-S3.yaml
> +  url: ""
url: "https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/v0.4.4/templates/S3/synapse-external-bucket.j2"

2022-07-27 16:07 UTC, zaro0508 commented on config/prod/PsychENCODE-Globus-S3.yaml
> +  OwnerEmail: 'dan.lu@sagebase.org'
these are no longer needed, please remove.

2022-07-27 16:08 UTC, zaro0508 commented on config/prod/PsychENCODE-Globus-S3.yaml
> +  EncryptBucket: 'false' # allow external users access to the bucket
We require buckets in scicomp to be encrypted.  It's set to encrypted by default so you can either remove this or comment it out.

2022-07-27 17:01 UTC, danlu1 commented on templates/PEC-Globus-S3.j2
> +AWSTemplateFormatVersion: 2010-09-09
I added s3:DeleteObject to the bucket policy. I saw there is a PR in aws-infra repo that might be ready to be merged. Can you check that?

2022-07-27 17:01 UTC, danlu1 commented on config/prod/PsychENCODE-Globus-S3.yaml
> +  CostCenter: "NO PROGRAM / 000000"
I don't find an appropriate code for my data. Can I apply one?

2022-07-27 17:16 UTC, zaro0508 commented on config/prod/PsychENCODE-Globus-S3.yaml
> +  CostCenter: "NO PROGRAM / 000000"
those codes come from finance @danlu1.  I would talk to finance to get new codes.

2022-07-27 17:53 UTC, danlu1 commented on config/prod/PsychENCODE-Globus-S3.yaml
> +  CostCenter: "NO PROGRAM / 000000"
@zaro0508 Thanks!!

2022-07-28 21:16 UTC, zaro0508 requested changes

2022-07-28 21:16 UTC, zaro0508 commented on config/prod/PsychENCODE-Globus-S3.yaml
> +  url: "https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/v0.4.4/templates/S3/synapse-external-bucket.j2"
```suggestion
  url: "https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/v0.4.5/templates/S3/synapse-external-bucket.j2"
```

2022-07-28 21:16 UTC, zaro0508 commented on config/prod/PsychENCODE-Globus-S3.yaml
> +  SynapseUserName: 'danlu'
we've replaced `SynapseUserName` with `SynapseIDs`.  please remove this line.

Please add this at the same level as `parameters:`
```
sceptre_user_data:
  SynapseIDs:
    - "3434599"
```

2022-07-28 23:46 UTC, danlu1 commented on config/prod/PsychENCODE-Globus-S3.yaml
> +  CostCenter: "NO PROGRAM / 000000"
@zaro0508 Thanks for you feedback, Khai. May I ask do we have an estimation time to get the cost center code? My director Mette is out this office, but she approved that we configure a separate S3 for this data transfer. If needed, I can share her approval message with finance team.

2022-07-29 15:29 UTC, zaro0508 commented on config/prod/PsychENCODE-Globus-S3.yaml
> +  CostCenter: "NO PROGRAM / 000000"
> May I ask do we have an estimation time to get the cost center code?

I'm not sure i understand your question @danlu1.  Finance is the one that can provide you with a cost center code.  IT has no control over that.  If it's taking too long we might be able to create a bucket now and apply a code retroactively but that might be a @brucehoff decision.

2022-07-29 15:37 UTC, brucehoff commented on config/prod/PsychENCODE-Globus-S3.yaml
> +  CostCenter: "NO PROGRAM / 000000"
Khai, I believe Dan is saying that her cost center is not listed  here: [template/tags folder](https://github.com/Sage-Bionetworks/aws-infra/tree/master/templates/tags) Assuming that the code has to be in our GitHub doc's I have a request in to Finance to confirm the updated list, and will update our doc's.  If it doesn't have to be in the GitHub doc's for Dan to enter it in this PR, then please do so, @danlu1 .

2022-07-29 18:10 UTC, danlu1 commented on config/prod/PsychENCODE-Globus-S3.yaml
> +  CostCenter: "NO PROGRAM / 000000"
@brucehoff @zaro0508 Thanks guys, the cost center code is neither in [template/tags folder](https://github.com/Sage-Bionetworks/aws-infra/tree/master/templates/tags) nor  [2022July28ChartOfAccounts.csv](https://github.com/Sage-Bionetworks/scicomp-provisioner/files/9222334/2022July28ChartOfAccounts.csv). I will reach out to finance and discuss this.

2022-08-08 03:23 UTC, thomasyu888 approved these changes

2022-08-08 15:30 UTC, zaro0508 requested changes

2022-08-08 15:30 UTC, zaro0508 commented on config/prod/PsychENCODE-Globus-S3.yaml
> +    - "3434599"
`sceptre_user_data:` needs to be at the same level as `parameters:`.  for example:

```
parameters:
  FirstParam: "foo"
  SecondParam: "bar"
sceptre_user_data:
  SynapseIDs:
    - "3434599"
```

2022-08-08 16:06 UTC, zaro0508 commented on config/prod/PsychENCODE-Globus-S3.yaml
> +    - 'arn:aws:sts::563295687221:assumed-role/AWSReservedSSO_Developer_baa6fed639faf5e7/dan.lu@sagebase.org'
please add `arn:aws:iam::531197219947:user/ucla-orion-transfer-user`

2022-08-08 17:03 UTC, zaro0508 requested changes

2022-08-08 17:03 UTC, zaro0508 commented on config/prod/PsychENCODE-Globus-S3.yaml
>      - "3434599"
GrantAccess goes with parameter, not sceptre_user_data.  Please move this section to the bottom of the file.

2022-08-08 18:43 UTC, zaro0508 approved these changes

2022-08-08 18:44 UTC, merged