S3 Buckets for RECOVER Project, Bucket 1: recover_input_shared_bucket
Sage-Bionetworks/scicomp-provisioner pull request #566
Opened 2023-03-17 23:21 UTC by itismeghasyam

1. (First Bucket) recover_input_shared_bucket: We receive data from Care Evolution in this bucket.

2023-03-17 23:23 UTC, itismeghasyam commented
PR #564 was split into two, this is one and the other is #565 

Changes from #564 -> Owner's email updated to the shared RECOVER account - 'synapse-service-sysbio-recover-data-storage-01@sagebase.org' from 'meghasyam@sageabase.org'

2023-03-20 19:54 UTC, jesusaurus requested changes

2023-03-20 19:54 UTC, jesusaurus commented on config/prod/recover-input-shared-bucket.yaml
> +  Department: "SysBio"
The `Department` and `Project` tags can be removed, they aren't needed or used.

2023-03-20 19:54 UTC, jesusaurus commented on config/prod/recover-input-shared-bucket.yaml
> +parameters:
Several of these parameters don't exist in [the template](https://github.com/Sage-Bionetworks/aws-infra/blob/v0.5.0/templates/S3/synapse-external-bucket.j2) (`Department`, `Project`, `OwnerEmail`, and `SynapseUserName`) and should be removed here.

2023-03-21 19:53 UTC, closed without merging