IT-2673: Move scicomp provisioner to GHA
Sage-Bionetworks/scicomp-provisioner pull request #567
Opened 2023-03-21 07:07 UTC by xschildw

This PR contains a GHA replacement for the existing Travis job.
NOTE: Don't merge before removing .travis.yaml

2023-03-21 07:08 UTC, xschildw commented on .yamllint
> -  quoted-strings:
This was not in aws-infra and would have required quoting every string.

2023-03-21 18:12 UTC, zaro0508 requested changes
please remove .travis.yml file and remember to clean up any secrets left on travis

2023-03-21 18:12 UTC, zaro0508 commented on .github/workflows/deploy.yaml
> +        uses: aws-actions/configure-aws-credentials@v1
it's v2 now https://github.com/marketplace/actions/configure-aws-credentials-for-github-actions

2023-03-21 18:12 UTC, zaro0508 commented on .github/workflows/deploy.yaml
> +name: "scicomp-provisioner-gha"
would make more sense if this was same as the filename

2023-03-21 19:28 UTC, zaro0508 approved these changes

2023-03-22 00:42 UTC, zaro0508 requested changes

2023-03-22 00:42 UTC, zaro0508 commented on .github/workflows/deploy.yaml
> +          sceptre_subcommand: 'launch -y prod'
we also want the `--prune` flag, https://github.com/Sage-Bionetworks/scicomp-provisioner/blob/master/.travis.yml#L30

2023-03-22 00:42 UTC, zaro0508 commented on .github/workflows/deploy.yaml
> +        with:
we also need to install the sceptre-ssm-resolver, https://github.com/Sage-Bionetworks/scicomp-provisioner/blob/master/.travis.yml#L14

2023-03-22 00:42 UTC, zaro0508 commented on .github/workflows/deploy.yaml
> +        uses: actions/checkout@master
we should use v3, not master   https://github.com/marketplace/actions/checkout

2023-03-22 16:05 UTC, zaro0508 approved these changes
looks good, just one minor update and it's good to go.

2023-04-14 00:09 UTC, zaro0508 approved these changes

2023-04-14 01:36 UTC, merged