Modify psychencode
Sage-Bionetworks/scicomp-provisioner pull request #620
Opened 2024-02-15 08:33 UTC by thomasyu888

Add DPE team so that we can test migration code first

2024-02-15 14:44 UTC, brucehoff approved these changes

2024-02-15 18:29 UTC, thomasyu888 commented on config/prod/psychencode-migration-bucket.yaml
>    SameRegionResourceAccessToBucket: 'true'
```suggestion
  # SameRegionResourceAccessToBucket: 'true'
```

2024-02-15 18:51 UTC, brucehoff requested changes
Why remove `SameRegionResourceAccessToBucket`?  I thought that protected us from data transfer charges.

2024-02-15 19:07 UTC, thomasyu888 commented on config/prod/psychencode-migration-bucket.yaml
> +    - "3453016" # DPE team
```suggestion
    - "3453016" # DPE team
    - "3357888" # Will
```

2024-02-16 18:17 UTC, brucehoff approved these changes

2024-02-16 18:18 UTC, merged